"""`ancal` command-line entry point."""

from __future__ import annotations

import argparse
import importlib
import shutil
import subprocess
import sys

from . import budget, status
from .settings import load_settings

REQUIRED_TOOLS = ("bcftools", "tabix", "bgzip", "samtools", "snakemake")
REQUIRED_MODULES = ("polars", "pyarrow", "pandas", "pydantic", "yaml", "requests", "fsspec")


def _tool_version(tool: str) -> str:
    out = subprocess.run([tool, "--version"], capture_output=True, text=True)
    return (out.stdout or out.stderr).splitlines()[0].strip() if (out.stdout or out.stderr) else "?"


def cmd_budget_check(args) -> int:
    s = load_settings(scope_override=args.scope)
    u = budget.usage(s)
    print(f"scope={s.scope}  budget={s.local_budget_gb} GB  used={u.used_mb:.1f} MB")
    for d, b in sorted(u.by_dir.items()):
        print(f"  {d:<32} {b / 1024**2:10.2f} MB")
    if not u.ok:
        print("OVER BUDGET - see SCALING_UP.md", file=sys.stderr)
        return 1
    return 0


def cmd_check_env(args) -> int:
    s = load_settings()
    checks = []
    for tool in REQUIRED_TOOLS:
        path = shutil.which(tool)
        checks.append(status.Check(f"tool:{tool}", path is not None, _tool_version(tool) if path else "not on PATH"))
    for mod in REQUIRED_MODULES:
        try:
            m = importlib.import_module(mod)
            checks.append(status.Check(f"python:{mod}", True, getattr(m, "__version__", "")))
        except ImportError as e:
            checks.append(status.Check(f"python:{mod}", False, str(e)))
    u = budget.usage(s)
    checks.append(status.Check("disk_budget", u.ok, f"{u.used_mb:.1f} MB of {s.local_budget_gb} GB"))
    if args.pytest_ok is not None:
        checks.append(status.Check("pytest", args.pytest_ok == "1", "unit tests"))

    st = status.write(s, "stage0", checks, notes="Environment and repository scaffold (item 1).")
    for c in checks:
        print(f"  [{'ok' if c.ok else 'FAIL'}] {c.name:<20} {c.detail}")
    print(f"stage0: {st.status}")
    return 0 if st.status == "pass" else 1


def cmd_validate_config(args) -> int:
    """Stage 1 gate: both config files validate; write the deferred-items review report."""
    from pydantic import ValidationError

    from . import config

    s = load_settings()
    checks, cfg = [], None
    for name, loader in (("analysis.yaml", config.load_analysis), ("data_sources.yaml", config.load_data_sources)):
        try:
            model = loader(s.root)
            checks.append(status.Check(f"schema:{name}", True, "valid"))
            if name == "analysis.yaml":
                cfg = model
        except (ValidationError, FileNotFoundError) as e:
            checks.append(status.Check(f"schema:{name}", False, str(e).replace("\n", " | ")))

    notes = "Draft analysis configuration (item 2)."
    if cfg is not None:
        items = config.deferred_items(cfg)
        by_status = {k: sum(d.status == k for _, d in items) for k in ("pending", "proposed", "confirmed")}
        notes += f" Deferred items: {by_status}. Not yet frozen."
        report = s.root / "reports" / "qc" / "config_status.md"
        rows = "\n".join(
            f"| `{p}` | {d.status} | {d.settled_in} | {d.note.strip() or '—'} |" for p, d in items
        )
        report.write_text(
            "# Analysis configuration: open items\n\n"
            "Generated by `ancal validate-config` from `config/analysis.yaml`. Do not edit.\n\n"
            "`ancal freeze-config` refuses to run until every row below is `confirmed`.\n"
            "The freeze happens after the Stage 9 review and before any performance analysis.\n\n"
            f"Pending: {by_status['pending']} · Proposed (needs team confirmation): "
            f"{by_status['proposed']} · Confirmed: {by_status['confirmed']}\n\n"
            "| Setting | Status | Settled in | Note |\n|---|---|---|---|\n"
            f"{rows}\n"
        )

    st = status.write(s, "stage1", checks, notes=notes)
    for c in checks:
        print(f"  [{'ok' if c.ok else 'FAIL'}] {c.name:<24} {c.detail}")
    print(f"stage1: {st.status}  {notes}")
    return 0 if st.status == "pass" else 1


def cmd_freeze_config(args) -> int:
    from . import config

    s = load_settings()
    try:
        out = config.freeze(s.root)
    except config.NotFreezable as e:
        print(e, file=sys.stderr)
        return 1
    print(f"Frozen: {out.relative_to(s.root)}")
    return 0


def cmd_status(args) -> int:
    s = load_settings()
    rows = status.read_all(s)
    if not rows:
        print("No stage has run yet.")
        return 0
    for r in rows:
        extra = f"  ({r['blocked_reason']})" if r.get("blocked_reason") else ""
        print(f"{r['stage']:<8} {r['status']:<8} scope={r['scope']:<10} disk={r['disk_used_mb']} MB{extra}")
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="ancal")
    sub = p.add_subparsers(dest="cmd", required=True)

    b = sub.add_parser("budget-check", help="Report local disk usage against the budget")
    b.add_argument("--scope", default=None)
    b.set_defaults(func=cmd_budget_check)

    e = sub.add_parser("check-env", help="Stage 0 gate: tools, imports, budget")
    e.add_argument("--pytest-ok", choices=("0", "1"), default=None)
    e.set_defaults(func=cmd_check_env)

    v = sub.add_parser("validate-config", help="Stage 1 gate: validate config files, report open items")
    v.set_defaults(func=cmd_validate_config)

    f = sub.add_parser("freeze-config", help="Freeze analysis.yaml (only when every item is confirmed)")
    f.set_defaults(func=cmd_freeze_config)

    st = sub.add_parser("status", help="Show the status of every stage run so far")
    st.set_defaults(func=cmd_status)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
